version: "0.5"

processes:
  0-postgresql:
    command: ./scripts/pgsql-start.sh
    readiness_probe:
      exec:
        command: docker exec silos-postgres pg_isready -U postgres
      initial_delay_seconds: 3
      period_seconds: 2
      timeout_seconds: 5

  1-check-connection:
    command: ./scripts/pgsql-check.sh
    depends_on:
      0-postgresql:
        condition: process_healthy
    availability:
      restart: "no"

